### ISSUE TITLE
Tag the current release using semantic versioning with "v" prefix

### ISSUE THREAD

**Issue by ghost** [miscel/owl-carousel-arrows#5]
To tag the release refer to the accepted answer: https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository

```sh
git tag <tagname>
git push origin --tags
```
Semantic versioning: http://semver.org/ (means major.minor.patch - With `v` prefix it would be something like `v1.0.0`)

tag it with `v1.0.0` and push the tag.

**Comment by miscel** [comment]
I need more details, I already created a tag "v1.0.0" but how can we use it?
